# Errors

```ts title="server.ts"
const isAuthed = middleware(({ ctx, next }) => {
  if (!ctx.user) throw new HTTPError({ code: 'UNAUTHORIZED', message: 'Must be logged in!' });

  return next({
    ctx: {
      user: ctx.user,
    },
  });
});
```

The `HTTPError` is the only error that is catched by the ptsq and the adapter after throw response with code.

| HTTPError code        | Status code |
| --------------------- | ----------- |
| BAD_REQUEST           | 400         |
| UNAUTHORIZED          | 401         |
| FORBIDDEN             | 403         |
| NOT_FOUND             | 404         |
| METHOD_NOT_SUPPORTED  | 405         |
| TIMEOUT               | 408         |
| CONFLICT              | 409         |
| PRECONDITION_FAILED   | 412         |
| PAYLOAD_TOO_LARGE     | 413         |
| UNPROCESSABLE_CONTENT | 422         |
| TOO_MANY_REQUESTS     | 429         |
| CLIENT_CLOSED_REQUEST | 499         |
| INTERNAL_SERVER_ERROR | 500         |

Any other exception, (non `HTTPError`) throws as normal, so it stops the server.
